version: "2"
services:
    client:
        image: webapp-client
        build: 
            context: ./millamoolah_client
            dockerfile: Dockerfile
        tty: true      
        restart: on-failure
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - server
        networks:
            - webappnetwork
    server:
        image: webapp-server
        build: ./millamoolah_server
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./server:/server
            - /server/node_modules
        depends_on:
            - mongodb
        networks:
            - webappnetwork
    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        ports:
            - 27017:27017
        networks:
            - webappnetwork
    mongo-seed:
        build: ./seed
        links:
            - mongodb
networks:
    webappnetwork:
        driver: bridge