version: "2"
services:
    client:
        build: 
            context: ./millamoolah_client
            dockerfile: Dockerfile.prod
        tty: true      
        restart: on-failure
        ports:
            - "80:80"
        volumes:
            - ./millamoolah_client/src:/client/src
        links:
            - server
        networks:
            - webappnetwork
    server:
        image: webapp-server
        build: ./millamoolah_server
        restart: always
        expose: [9000]
        volumes:
            - ./millamoolah_server:/server
        depends_on:
            - mongodb
        networks:
            - webappnetwork
    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        ports:
            - 27017:27017
        networks:
            - webappnetwork
    mongo-seed:
        build: ./seed
        links:
            - mongodb
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge